# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ays/2A/CHP PARAF"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ays/2A/CHP PARAF"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ays/2A/CHP PARAF/CMakeFiles" "/home/ays/2A/CHP PARAF//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ays/2A/CHP PARAF/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHP

# Build rule for target.
CHP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CHP
.PHONY : CHP

# fast build rule for target.
CHP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/build
.PHONY : CHP/fast

BiCGstab.o: BiCGstab.cpp.o
.PHONY : BiCGstab.o

# target to build an object file
BiCGstab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/BiCGstab.cpp.o
.PHONY : BiCGstab.cpp.o

BiCGstab.i: BiCGstab.cpp.i
.PHONY : BiCGstab.i

# target to preprocess a source file
BiCGstab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/BiCGstab.cpp.i
.PHONY : BiCGstab.cpp.i

BiCGstab.s: BiCGstab.cpp.s
.PHONY : BiCGstab.s

# target to generate assembly for a file
BiCGstab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/BiCGstab.cpp.s
.PHONY : BiCGstab.cpp.s

Matrice.o: Matrice.cpp.o
.PHONY : Matrice.o

# target to build an object file
Matrice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrice.cpp.o
.PHONY : Matrice.cpp.o

Matrice.i: Matrice.cpp.i
.PHONY : Matrice.i

# target to preprocess a source file
Matrice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrice.cpp.i
.PHONY : Matrice.cpp.i

Matrice.s: Matrice.cpp.s
.PHONY : Matrice.s

# target to generate assembly for a file
Matrice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrice.cpp.s
.PHONY : Matrice.cpp.s

fonctions.o: fonctions.cpp.o
.PHONY : fonctions.o

# target to build an object file
fonctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/fonctions.cpp.o
.PHONY : fonctions.cpp.o

fonctions.i: fonctions.cpp.i
.PHONY : fonctions.i

# target to preprocess a source file
fonctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/fonctions.cpp.i
.PHONY : fonctions.cpp.i

fonctions.s: fonctions.cpp.s
.PHONY : fonctions.s

# target to generate assembly for a file
fonctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/fonctions.cpp.s
.PHONY : fonctions.cpp.s

read.o: read.cpp.o
.PHONY : read.o

# target to build an object file
read.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/read.cpp.o
.PHONY : read.cpp.o

read.i: read.cpp.i
.PHONY : read.i

# target to preprocess a source file
read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/read.cpp.i
.PHONY : read.cpp.i

read.s: read.cpp.s
.PHONY : read.s

# target to generate assembly for a file
read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/read.cpp.s
.PHONY : read.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CHP"
	@echo "... BiCGstab.o"
	@echo "... BiCGstab.i"
	@echo "... BiCGstab.s"
	@echo "... Matrice.o"
	@echo "... Matrice.i"
	@echo "... Matrice.s"
	@echo "... fonctions.o"
	@echo "... fonctions.i"
	@echo "... fonctions.s"
	@echo "... read.o"
	@echo "... read.i"
	@echo "... read.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

